/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexao.ConnectionFactory;
import java.sql.Connection;

/**
 *
 * @author Lider
 */
public class ViewPrincipal extends javax.swing.JFrame {
     private Connection connection;

    /**
     * Creates new form View
     */
    public ViewPrincipal() {
        initComponents();
        
         try{
            this.connection = ConnectionFactory.getConnection();
            ConnectionFactory.checkDatabase();
        }
        catch(Exception e)
        {
            System.out.println("Erro na abertura do banco de dados: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroCarro = new javax.swing.JButton();
        cadastroPessoa = new javax.swing.JButton();
        atualizaCarro = new javax.swing.JButton();
        atualizaPessoa = new javax.swing.JButton();
        excluiCarro = new javax.swing.JButton();
        excluiPessoa = new javax.swing.JButton();
        mostraCarros = new javax.swing.JButton();
        mostraPesoa = new javax.swing.JButton();
        alugaCarro = new javax.swing.JButton();
        mostraCarroAlugado = new javax.swing.JButton();
        fecharJanela = new javax.swing.JButton();
        botaoTodasLocacoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastroCarro.setText("Cadastro Carro");
        cadastroCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCarroActionPerformed(evt);
            }
        });

        cadastroPessoa.setText("Cadastro Pessoa");
        cadastroPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPessoaActionPerformed(evt);
            }
        });

        atualizaCarro.setText("Ataualização dados carro");
        atualizaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaCarroActionPerformed(evt);
            }
        });

        atualizaPessoa.setText("Atualização dados pessoa");
        atualizaPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaPessoaActionPerformed(evt);
            }
        });

        excluiCarro.setText("Exclusão carro");
        excluiCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluiCarroActionPerformed(evt);
            }
        });

        excluiPessoa.setText("Exclusão Pessoa");
        excluiPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluiPessoaActionPerformed(evt);
            }
        });

        mostraCarros.setText("Todos carros cadastrados");
        mostraCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostraCarrosActionPerformed(evt);
            }
        });

        mostraPesoa.setText("Todos pessoa cadastros");
        mostraPesoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostraPesoaActionPerformed(evt);
            }
        });

        alugaCarro.setText("Alugar carros");
        alugaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alugaCarroActionPerformed(evt);
            }
        });

        mostraCarroAlugado.setText("Carros disponíveis");
        mostraCarroAlugado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostraCarroAlugadoActionPerformed(evt);
            }
        });

        fecharJanela.setText("Fechar");
        fecharJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharJanelaActionPerformed(evt);
            }
        });

        botaoTodasLocacoes.setText("Todas locações");
        botaoTodasLocacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTodasLocacoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mostraCarros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(excluiCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(atualizaCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cadastroCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(atualizaPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(cadastroPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(excluiPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mostraPesoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(alugaCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mostraCarroAlugado, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(botaoTodasLocacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(fecharJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadastroPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(alugaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cadastroCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mostraCarroAlugado, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(atualizaCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atualizaPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoTodasLocacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(excluiCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(excluiPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mostraCarros, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(mostraPesoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addComponent(fecharJanela)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCarroActionPerformed
       ViewCadastroCarro cadCarro = new ViewCadastroCarro();
       cadCarro.setVisible(true);
    }//GEN-LAST:event_cadastroCarroActionPerformed

    private void alugaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alugaCarroActionPerformed
       ViewAlugar alugaCarro = new ViewAlugar();
       alugaCarro.setVisible(true);
    }//GEN-LAST:event_alugaCarroActionPerformed

    private void fecharJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharJanelaActionPerformed
        setVisible(false);
    }//GEN-LAST:event_fecharJanelaActionPerformed

    private void cadastroPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPessoaActionPerformed
        ViewCadastroPessoa cadPessoa = new ViewCadastroPessoa();
        cadPessoa.setVisible(true);
    }//GEN-LAST:event_cadastroPessoaActionPerformed

    private void atualizaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaCarroActionPerformed
        ViewAtualizacaoCarro atualizaCarro = new ViewAtualizacaoCarro();
        atualizaCarro.setVisible(true);
    }//GEN-LAST:event_atualizaCarroActionPerformed

    private void atualizaPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaPessoaActionPerformed
        ViewAtualizacaoPessoa atualizaPessoa = new ViewAtualizacaoPessoa();
        atualizaPessoa.setVisible(true);
    }//GEN-LAST:event_atualizaPessoaActionPerformed

    private void excluiCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluiCarroActionPerformed
        ViewExclucaoCarro exclusaoCarro = new ViewExclucaoCarro();
        exclusaoCarro.setVisible(true);
    }//GEN-LAST:event_excluiCarroActionPerformed

    private void excluiPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluiPessoaActionPerformed
        ViewExclusaoPessoa exclusaoPessoa = new ViewExclusaoPessoa();
        exclusaoPessoa.setVisible(true);
    }//GEN-LAST:event_excluiPessoaActionPerformed

    private void mostraCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostraCarrosActionPerformed
        ViewMostrarCarros mostraCarros = new ViewMostrarCarros();
        mostraCarros.setVisible(true);
    }//GEN-LAST:event_mostraCarrosActionPerformed

    private void mostraPesoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostraPesoaActionPerformed
        ViewMostrarPessoas mostraPessoas = new ViewMostrarPessoas();
        mostraPessoas.setVisible(true);
    }//GEN-LAST:event_mostraPesoaActionPerformed

    private void mostraCarroAlugadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostraCarroAlugadoActionPerformed
        ViewMostrarAlugados mostraAlugados = new ViewMostrarAlugados();
        mostraAlugados.setVisible(true);
    }//GEN-LAST:event_mostraCarroAlugadoActionPerformed

    private void botaoTodasLocacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTodasLocacoesActionPerformed
        ViewTodasLocacoes todasLocacoes = new ViewTodasLocacoes();
        todasLocacoes.setVisible(true);
    }//GEN-LAST:event_botaoTodasLocacoesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alugaCarro;
    private javax.swing.JButton atualizaCarro;
    private javax.swing.JButton atualizaPessoa;
    private javax.swing.JButton botaoTodasLocacoes;
    private javax.swing.JButton cadastroCarro;
    private javax.swing.JButton cadastroPessoa;
    private javax.swing.JButton excluiCarro;
    private javax.swing.JButton excluiPessoa;
    private javax.swing.JButton fecharJanela;
    private javax.swing.JButton mostraCarroAlugado;
    private javax.swing.JButton mostraCarros;
    private javax.swing.JButton mostraPesoa;
    // End of variables declaration//GEN-END:variables

    
}
